### ISSUE TITLE
道长：两个小问题。

### ISSUE THREAD

**Issue by mengxiabing** [CN-ZPH/Three360panorama#2]
下载的DEMO，
1，拿着手机转了180度，图片却转了360度，不知道是否我的使用方法有误。
2，把图片转了很多圈，点击指示器复位图片位置时候，逆向也转了很多圈，是否可以优化下。

**Comment by CN-ZPH** [comment]
第一个你转180那是因为我乘以了2.0，好好看文章去。对啊我故意弄的复位过渡效果，你前面怎么转我就这么复位。你们总是不看清楚文章，我文章里写的很清楚你直接修改复位就可以。

**Comment by tcqq** [comment]
你发什么火

**Comment by CN-ZPH** [comment]
哥们你这就误会我了，可能我表达的有问题。只是建议你看完文章，如果项目上有问题我随时欢迎你们来反馈，抱歉！
